pyuic6 ./ui/Import_Cookies.ui -o ./ui_code_raw/Import_Cookies.py
pyuic6 ./ui/Config_Window.ui -o ./ui_code_raw/Config_Window.py
pyuic6 ./ui/Result_Insert_Cookie.ui -o ./ui_code_raw/Result_Insert_Cookie.py
pyuic6 ./ui/Import_Proxy.ui -o ./ui_code_raw/Import_Proxy.py
pyuic6 ./ui/Proxy_Item.ui -o ./ui_code_raw/Proxy_Item.py
pyuic6 ./ui/Manage_Facebook_Account.ui -o ./ui_code_raw/Manage_Facebook_Account.py
pyuic6 ./ui/Facebook_Account_Item.ui -o ./ui_code_raw/Facebook_Account_Item.py
pyuic6 ./ui/Proxy_Manager.ui -o ./ui_code_raw/Proxy_Manager.py
pyuic6 ./ui/Share_Permission.ui -o ./ui_code_raw/Share_Permission.py
pyuic6 ./ui/Remove_Permission.ui -o ./ui_code_raw/Remove_Permission.py
