# Form implementation generated from reading ui file './ui/Import_Proxy.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImportProxy(object):
    def setupUi(self, ImportProxy):
        ImportProxy.setObjectName("ImportProxy")
        ImportProxy.resize(650, 557)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportProxy)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_list_proxy = QtWidgets.QScrollArea(ImportProxy)
        self.scrollArea_list_proxy.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollArea_list_proxy.setWidgetResizable(True)
        self.scrollArea_list_proxy.setObjectName("scrollArea_list_proxy")
        self.scrollAreaWidgetContents_list_proxy = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_list_proxy.setGeometry(QtCore.QRect(0, -19, 613, 318))
        self.scrollAreaWidgetContents_list_proxy.setObjectName("scrollAreaWidgetContents_list_proxy")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_list_proxy)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_list_account = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_list_proxy)
        self.tableWidget_list_account.setMinimumSize(QtCore.QSize(0, 300))
        self.tableWidget_list_account.setObjectName("tableWidget_list_account")
        self.tableWidget_list_account.setColumnCount(0)
        self.tableWidget_list_account.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_list_account)
        self.scrollArea_list_proxy.setWidget(self.scrollAreaWidgetContents_list_proxy)
        self.verticalLayout.addWidget(self.scrollArea_list_proxy)
        self.plainTextEdit_Import_Proxy = QtWidgets.QPlainTextEdit(ImportProxy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.plainTextEdit_Import_Proxy.setFont(font)
        self.plainTextEdit_Import_Proxy.setPlaceholderText("")
        self.plainTextEdit_Import_Proxy.setObjectName("plainTextEdit_Import_Proxy")
        self.verticalLayout.addWidget(self.plainTextEdit_Import_Proxy)
        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(ImportProxy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.plainTextEdit_result.setFont(font)
        self.plainTextEdit_result.setPlainText("")
        self.plainTextEdit_result.setPlaceholderText("")
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.verticalLayout.addWidget(self.plainTextEdit_result)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ImportProxy)
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_count_proxy = QtWidgets.QLabel(ImportProxy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_count_proxy.setFont(font)
        self.label_count_proxy.setObjectName("label_count_proxy")
        self.horizontalLayout_2.addWidget(self.label_count_proxy)
        self.pushButton_Insert = QtWidgets.QPushButton(ImportProxy)
        self.pushButton_Insert.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Insert.setFont(font)
        self.pushButton_Insert.setObjectName("pushButton_Insert")
        self.horizontalLayout_2.addWidget(self.pushButton_Insert)
        self.pushButton_Read = QtWidgets.QPushButton(ImportProxy)
        self.pushButton_Read.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Read.setFont(font)
        self.pushButton_Read.setObjectName("pushButton_Read")
        self.horizontalLayout_2.addWidget(self.pushButton_Read)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ImportProxy)
        QtCore.QMetaObject.connectSlotsByName(ImportProxy)

    def retranslateUi(self, ImportProxy):
        _translate = QtCore.QCoreApplication.translate
        ImportProxy.setWindowTitle(_translate("ImportProxy", "Import Proxy"))
        self.plainTextEdit_Import_Proxy.setPlainText(_translate("ImportProxy", "103.172.235.29:3253:sasamviet:f518a0661\n"
"103.172.234.170:3253:sasamviet:f518a0661\n"
"103.172.235.31:3253:sasamviet:f518a0661\n"
"103.172.234.163:3253:sasamviet:f518a0661\n"
"103.172.235.179:3253:sasamviet:f518a0661\n"
"IP_0:PORT_0:USERNAME_0:PASSWORD_0\n"
"IP_1:PORT_1:USERNAME_1:PASSWORD_1\n"
"IP_2:PORT_2:USERNAME_2:PASSWORD_2"))
        self.label_2.setText(_translate("ImportProxy", "Count:"))
        self.label_count_proxy.setText(_translate("ImportProxy", "0"))
        self.pushButton_Insert.setText(_translate("ImportProxy", "Insert"))
        self.pushButton_Read.setText(_translate("ImportProxy", "Read"))
