# Form implementation generated from reading ui file './ui/Install_Proxy.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Install_Proxy(object):
    def setupUi(self, Form_Install_Proxy):
        Form_Install_Proxy.setObjectName("Form_Install_Proxy")
        Form_Install_Proxy.resize(720, 434)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_Install_Proxy)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_Input = QtWidgets.QPlainTextEdit(Form_Install_Proxy)
        self.plainTextEdit_Input.setReadOnly(True)
        self.plainTextEdit_Input.setObjectName("plainTextEdit_Input")
        self.verticalLayout.addWidget(self.plainTextEdit_Input)
        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(Form_Install_Proxy)
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.verticalLayout.addWidget(self.plainTextEdit_result)
        self.groupBox_3 = QtWidgets.QGroupBox(Form_Install_Proxy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_input = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_input.setObjectName("radioButton_input")
        self.horizontalLayout_2.addWidget(self.radioButton_input)
        self.radioButton_disable = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_disable.setObjectName("radioButton_disable")
        self.horizontalLayout_2.addWidget(self.radioButton_disable)
        self.radioButton_enable = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_enable.setObjectName("radioButton_enable")
        self.horizontalLayout_2.addWidget(self.radioButton_enable)
        self.radioButton_all = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_all.setChecked(True)
        self.radioButton_all.setObjectName("radioButton_all")
        self.horizontalLayout_2.addWidget(self.radioButton_all)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_user_code = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_user_code.setObjectName("comboBox_user_code")
        self.verticalLayout_4.addWidget(self.comboBox_user_code)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Form_Install_Proxy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_install = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_install.setObjectName("pushButton_install")
        self.horizontalLayout.addWidget(self.pushButton_install)
        self.pushButton_uninstall = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_uninstall.setObjectName("pushButton_uninstall")
        self.horizontalLayout.addWidget(self.pushButton_uninstall)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form_Install_Proxy)
        QtCore.QMetaObject.connectSlotsByName(Form_Install_Proxy)

    def retranslateUi(self, Form_Install_Proxy):
        _translate = QtCore.QCoreApplication.translate
        Form_Install_Proxy.setWindowTitle(_translate("Form_Install_Proxy", "Install proxy"))
        self.groupBox_3.setTitle(_translate("Form_Install_Proxy", "Action"))
        self.radioButton_input.setText(_translate("Form_Install_Proxy", "Input"))
        self.radioButton_disable.setText(_translate("Form_Install_Proxy", "Disable Account"))
        self.radioButton_enable.setText(_translate("Form_Install_Proxy", "Enable Account"))
        self.radioButton_all.setText(_translate("Form_Install_Proxy", "All Account"))
        self.groupBox_4.setTitle(_translate("Form_Install_Proxy", "User Code"))
        self.groupBox.setTitle(_translate("Form_Install_Proxy", "Action"))
        self.pushButton_install.setText(_translate("Form_Install_Proxy", "Install proxy"))
        self.pushButton_uninstall.setText(_translate("Form_Install_Proxy", "Uninstall Proxy"))
