# Form implementation generated from reading ui file './ui/Manage_Facebook_Account.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Manage_Facebook_Account(object):
    def setupUi(self, Manage_Facebook_Account):
        Manage_Facebook_Account.setObjectName("Manage_Facebook_Account")
        Manage_Facebook_Account.resize(800, 670)
        self.centralwidget = QtWidgets.QWidget(Manage_Facebook_Account)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_list_facebook_account = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_list_facebook_account.setWidgetResizable(True)
        self.scrollArea_list_facebook_account.setObjectName("scrollArea_list_facebook_account")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 482))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_list_facebook_account = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_list_facebook_account.setObjectName("verticalLayout_list_facebook_account")
        self.scrollArea_list_facebook_account.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea_list_facebook_account)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.label_result_api = QtWidgets.QLabel(self.centralwidget)
        self.label_result_api.setText("")
        self.label_result_api.setObjectName("label_result_api")
        self.verticalLayout.addWidget(self.label_result_api)
        Manage_Facebook_Account.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Manage_Facebook_Account)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Manage_Facebook_Account.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Manage_Facebook_Account)
        self.statusbar.setObjectName("statusbar")
        Manage_Facebook_Account.setStatusBar(self.statusbar)

        self.retranslateUi(Manage_Facebook_Account)
        QtCore.QMetaObject.connectSlotsByName(Manage_Facebook_Account)

    def retranslateUi(self, Manage_Facebook_Account):
        _translate = QtCore.QCoreApplication.translate
        Manage_Facebook_Account.setWindowTitle(_translate("Manage_Facebook_Account", "Facebook_Account"))
        self.groupBox_3.setTitle(_translate("Manage_Facebook_Account", "Master code Taget"))
        self.pushButton_3.setText(_translate("Manage_Facebook_Account", "Distribution"))
        self.groupBox_2.setTitle(_translate("Manage_Facebook_Account", "User code Taget"))
        self.pushButton_2.setText(_translate("Manage_Facebook_Account", "Distribution"))
        self.pushButton.setText(_translate("Manage_Facebook_Account", "Reload"))
