# Form implementation generated from reading ui file './ui/Remove_Permission.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Remove_Permission(object):
    def setupUi(self, Form_Remove_Permission):
        Form_Remove_Permission.setObjectName("Form_Remove_Permission")
        Form_Remove_Permission.resize(739, 522)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_Remove_Permission)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form_Remove_Permission)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 207))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_list_account = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget_list_account.setObjectName("tableWidget_list_account")
        self.tableWidget_list_account.setColumnCount(0)
        self.tableWidget_list_account.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget_list_account)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(Form_Remove_Permission)
        self.plainTextEdit_result.setReadOnly(True)
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.verticalLayout.addWidget(self.plainTextEdit_result)
        self.groupBox = QtWidgets.QGroupBox(Form_Remove_Permission)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_remove_permission = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_remove_permission.setObjectName("pushButton_remove_permission")
        self.horizontalLayout.addWidget(self.pushButton_remove_permission)
        self.comboBox_user_code = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_user_code.setObjectName("comboBox_user_code")
        self.horizontalLayout.addWidget(self.comboBox_user_code)
        self.verticalLayout.addWidget(self.groupBox)
        self.label_result = QtWidgets.QLabel(Form_Remove_Permission)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form_Remove_Permission)
        QtCore.QMetaObject.connectSlotsByName(Form_Remove_Permission)

    def retranslateUi(self, Form_Remove_Permission):
        _translate = QtCore.QCoreApplication.translate
        Form_Remove_Permission.setWindowTitle(_translate("Form_Remove_Permission", "Remove permission"))
        self.groupBox.setTitle(_translate("Form_Remove_Permission", "Action"))
        self.pushButton_remove_permission.setText(_translate("Form_Remove_Permission", "Remove permission"))
