# Form implementation generated from reading ui file './ui/Share_Permission.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Share_Permission(object):
    def setupUi(self, Form_Share_Permission):
        Form_Share_Permission.setObjectName("Form_Share_Permission")
        Form_Share_Permission.resize(739, 408)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_Share_Permission)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_list_uid = QtWidgets.QPlainTextEdit(Form_Share_Permission)
        self.plainTextEdit_list_uid.setObjectName("plainTextEdit_list_uid")
        self.verticalLayout.addWidget(self.plainTextEdit_list_uid)
        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(Form_Share_Permission)
        self.plainTextEdit_result.setReadOnly(True)
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.verticalLayout.addWidget(self.plainTextEdit_result)
        self.groupBox = QtWidgets.QGroupBox(Form_Share_Permission)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_random = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_random.setObjectName("checkBox_random")
        self.verticalLayout_2.addWidget(self.checkBox_random)
        self.lineEdit_number_account = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_number_account.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_number_account.setReadOnly(True)
        self.lineEdit_number_account.setObjectName("lineEdit_number_account")
        self.verticalLayout_2.addWidget(self.lineEdit_number_account)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.pushButton_share_permission = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_share_permission.setObjectName("pushButton_share_permission")
        self.horizontalLayout.addWidget(self.pushButton_share_permission)
        self.comboBox_user_code = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_user_code.setObjectName("comboBox_user_code")
        self.horizontalLayout.addWidget(self.comboBox_user_code)
        self.verticalLayout.addWidget(self.groupBox)
        self.label_result = QtWidgets.QLabel(Form_Share_Permission)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form_Share_Permission)
        QtCore.QMetaObject.connectSlotsByName(Form_Share_Permission)

    def retranslateUi(self, Form_Share_Permission):
        _translate = QtCore.QCoreApplication.translate
        Form_Share_Permission.setWindowTitle(_translate("Form_Share_Permission", "Share permission"))
        self.groupBox.setTitle(_translate("Form_Share_Permission", "Action"))
        self.groupBox_2.setTitle(_translate("Form_Share_Permission", "Random"))
        self.checkBox_random.setText(_translate("Form_Share_Permission", "Random account"))
        self.lineEdit_number_account.setPlaceholderText(_translate("Form_Share_Permission", "Enter number account"))
        self.pushButton_share_permission.setText(_translate("Form_Share_Permission", "Share permission"))
